// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };  define(['./interval'], function(Interval) {
    var ChronosDom;

    ChronosDom = (function() {
      function ChronosDom() {}

      ChronosDom.prototype.element = function(domId) {
        var domObject, domSearcher;

        if (typeof domId === 'string') {
          domSearcher = domId[0] === '#' ? domId.substring(1, domId.length) : domId;
          domObject = document.getElementById(domSearcher);
        } else {
          domObject = domId;
        }
        if (domObject == null) {
          throw new Error("Element " + domId + " not found");
        }
        return domObject;
      };

      ChronosDom.prototype.setText = function(element, text) {
        if (typeof element.text === 'function') {
          return element.text(text);
        } else {
          return element.innerHTML = text;
        }
      };

      ChronosDom.prototype.live = function(domId, callback, context, interval) {
        var domObject,
          _this = this;

        if (interval == null) {
          interval = '5 seconds';
        }
        domObject = this.element(domId);
        this.setText(domObject, callback(context));
        return new Interval({
          timeString: interval
        })["do"](function() {
          return _this.setText(domObject, callback(context));
        });
      };

      return ChronosDom;

    })();
    return new ChronosDom;
  });

}).call(this);
