// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function() {
    var ChronosError;

    return ChronosError = (function(_super) {
      __extends(ChronosError, _super);

      ChronosError.prototype.name = 'ChronosError';

      function ChronosError(message) {
        this.message = message;
      }

      return ChronosError;

    })(Error);
  });

}).call(this);
