// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };  define(['./interval'], function(Interval) {
    var ChronosConfig;

    ChronosConfig = (function() {
      function ChronosConfig() {}

      ChronosConfig.prototype.get = function(property) {
        return this[property]();
      };

      ChronosConfig.prototype.timezone = function() {
        var _ref;

        if ((typeof process !== "undefined" && process !== null ? (_ref = process.env) != null ? _ref.TZ : void 0 : void 0) != null) {
          return process.env.TZ;
        } else {
          return 'unknown';
        }
      };

      ChronosConfig.prototype.timezoneOffset = function() {
        return new Date().getTimezoneOffset();
      };

      ChronosConfig.prototype.timezoneCode = function() {
        return new Date().toUTCString().split(' ')[5];
      };

      return ChronosConfig;

    })();
    return new ChronosConfig;
  });

}).call(this);
