// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['./chronos_error'], function(ChronosError) {
    var Config;

    Config = (function() {
      function Config() {}

      Config.prototype.recognizedParameters = ['locale'];

      Config.prototype.set = function(param, value) {
        if (__indexOf.call(this.recognizedParameters, param) < 0) {
          throw new ChronosError("Unrecognized config parameter: " + param);
        }
        return this[param] = value;
      };

      Config.prototype.handle = function(property, value) {
        var param, val, _results;

        if (typeof property === 'string') {
          if (!value) {
            return this[property];
          }
          return this.set(property, value);
        } else {
          _results = [];
          for (param in property) {
            val = property[param];
            _results.push(this.set(param, val));
          }
          return _results;
        }
      };

      return Config;

    })();
    return new Config;
  });

}).call(this);
