// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };
  var privateMethods;

  privateMethods = {
    timezone: function() {
      var _ref;

      if ((typeof process !== "undefined" && process !== null ? (_ref = process.env) != null ? _ref.TZ : void 0 : void 0) != null) {
        return process.env.TZ;
      } else {
        return 'unknown';
      }
    },
    timezoneOffset: function() {
      return new Date().getTimezoneOffset();
    },
    timezoneCode: function() {
      return new Date().toUTCString().split(' ')[5];
    }
  };

  define(['./interval'], function(Interval) {
    var Info;

    Info = (function() {
      function Info() {}

      Info.prototype.get = function(property) {
        return privateMethods[property]();
      };

      return Info;

    })();
    return new Info;
  });

}).call(this);
