// Generated by CoffeeScript 1.6.2
(function() {
  if (typeof define !== 'function') { var define = require('amdefine')(module); };  define(['./time_utils'], function(TimeUtils) {
    var TimeSpan;

    return TimeSpan = (function() {
      function TimeSpan(milliseconds) {
        this.ms = milliseconds;
      }

      TimeSpan.prototype._round = function(divisor) {
        return Math.round(this.ms / divisor);
      };

      TimeSpan.prototype.milliseconds = function() {
        return this.ms;
      };

      TimeSpan.prototype.seconds = function() {
        return this._round(TimeUtils.SECOND_MS);
      };

      TimeSpan.prototype.minutes = function() {
        return this._round(TimeUtils.MINUTE_MS);
      };

      TimeSpan.prototype.hours = function() {
        return this._round(TimeUtils.HOUR_MS);
      };

      TimeSpan.prototype.days = function() {
        return this._round(TimeUtils.DAY_MS);
      };

      TimeSpan.prototype.weeks = function() {
        return this._round(TimeUtils.WEEK_MS);
      };

      TimeSpan.prototype.months = function() {
        return this._round(TimeUtils.MONTH_MS);
      };

      TimeSpan.prototype.years = function() {
        return this._round(TimeUtils.YEAR_MS);
      };

      return TimeSpan;

    })();
  });

}).call(this);
